### ISSUE TITLE
OAuth implementation research

### ISSUE THREAD

**Issue by gerasimig** [Andrii-Ishchenko/ELib#36]

**Comment by gerasimig** [comment]
base information here: http://www.asp.net/web-api/overview/security

**Comment by Andrii-Ishchenko** [comment]
webapi security book https://it-ebooks.info/book/2328/

**Comment by Andrii-Ishchenko** [comment]
information as well there : http://www.asp.net/mvc/overview/older-versions/using-oauth-providers-with-mvc
