### ISSUE TITLE
research possible angular architectures and develop angular project skeleton

### ISSUE THREAD

**Issue by forestNavka** [Andrii-Ishchenko/ELib#49]

**Comment by forestNavka** [comment]
I had seen  two approaches in the structure of angular app. The first one is group components by their  type : controllers in controllers folder, views in views, services in services folder.
http://www.johnpapa.net/structuring-an-angular-project/

Another one - group components by features.
http://cliffmeyers.com/blog/2013/4/21/code-organization-angularjs-javascript
http://www.johnpapa.net/angular-growth-structure/

**Comment by forestNavka** [comment]
I prefer the second approach. But it can be discussed. 
![screenshot_1](https://cloud.githubusercontent.com/assets/12857743/9378212/4ba869b0-4728-11e5-84b0-1373b9be933a.png)

**Comment by forestNavka** [comment]
The link to styleguide https://github.com/johnpapa/angular-styleguide

**Comment by Andrii-Ishchenko** [comment]
links to angularjs tutorials: http://www.designyourway.net/blog/resources/so-you-want-to-learn-angularjs-start-with-these-tutorials-and-resources/
